test = {   'name': 'q2_5',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> third_highest != 'Crime, Drama, Mystery' # You want the genre with the third highest average rating, not the third most common genre\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> isinstance(third_highest, str)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
