test = {   'name': 'q2_2',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> import numbers\n>>> isinstance(states_not_varieties, numbers.Integral) and isinstance(varieties_not_states, numbers.Integral)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> varieties_not_states - states_not_varieties > 50 # There is a large difference between the two values!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(states_not_varieties ** 7 / 5 * 8 % 9 ** 4 % 3 * 6) == 4 # Try again!\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> int(varieties_not_states ** 8 / 3 % 6 * 5 ** 9 % 9 * 8) == 48 # Try again!\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
